name: UIHC Style Guide
pygments: true
permalink: /:categories/:title.html
baseurl: http://hc-webcom.github.io/uihc-styleguide #this is just for the gh-pages branch run * jekyll serve --watch --baseurl='' * locally